### ISSUE TITLE
fast-logger fails to build with directory >=1.3.8

### ISSUE THREAD

**Issue by Merivuokko** [kazu-yamamoto/logger#204]
Building fast-logger with directory >>=1.3.8 fails, due to System.Directory module no more is Safe Haskell.

directory >=1.3.8 is necessary for packages utilizing support for Abstract filepath proposal AFPP.

**Comment by mniip** [comment]
Hello, would it be possible to make hackage revisions for previous fast-logger versions affected by this issue? Specifically `fast-logger >=3.0.3 && <=3.1.1` should have a `directory <1.3.8.0` constraint added.

**Comment by kazu-yamamoto** [comment]
I have several questions:

1) What is the advantage of Safe Haskell? I have read the paper some years ago but I don't understand it.
2) How is building failure relating to Safe Haskell?
3) Should fast-logger 3.2.x also have `directory <1.3.8.0`?

**Comment by mniip** [comment]
> 1. What is the advantage of Safe Haskell? I have read the paper some years ago but I don't understand it.

My understanding is: none. Because its design made it not applicable for most use cases, see https://discourse.haskell.org/t/deprecating-safe-haskell-or-heavily-investing-in-it/5489 for an extended discussion.

> 2. How is building failure relating to Safe Haskell?

The error message is as follows:
```
[ 9 of 11] Compiling System.Log.FastLogger.File ( System/Log/FastLogger/File.hs, dist/build/System/Log/FastLogger/File.o )               
                                                                                                                                         
System/Log/FastLogger/File.hs:12:1: error:                                                                                               
    System.Directory: Can't be safely imported!                                                                                          
    The module itself isn't safe.                                                                                                        
   |                                                                                                                                     
12 | import System.Directory (doesFileExist, doesDirectoryExist, getPermissions, writable, renameFile)                                   
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
`System.Log.FastLogger.File` is trying to declare itself Safe, but a module it imports -- `System.Directory` -- isn't Safe.

`System.Directory` used to be Safe, but [`directory-1.3.8.0` changelogs](https://hackage.haskell.org/package/directory-1.3.8.0/changelog) indicate that this has changed in 1.3.8.0. The module used to be Safe-inferred, meaning its safety is dependent in a fragile way on the safety of the things it imports. Exactly because of the AFPP, in `directory-1.3.8.0`, `System.Directory` started importing `System.OsPath` which is not Safe, meaning `System.Directory` was no longer Safe-inferred.

Some have argued that this breaks PVP in `directory`: https://github.com/haskell/directory/issues/147 . The consensus was that you shouldn't use Safe Haskell.

> 3. Should fast-logger 3.2.x also have `directory <1.3.8.0`?

`fast-logger >=3.1.2` is unaffected by this issue, because the fix in 35d4f89310004ae58f20f23a53631ac4d08e8018 has landed in 3.1.2.

3.2.x seems to still build fine against `directory >=1.3.8.0` on my machine.

**Comment by kazu-yamamoto** [comment]
- [x] 3.0.3
- [x] 3.0.4
- [x] 3.0.5
- [x] 3.1.0
- [x] 3.1.1

**Comment by kazu-yamamoto** [comment]
Sorry for the delay.
`directory >=1.3.8.0` is added to the versions above.
Can we close this issue?
