### ISSUE TITLE
Invert monad-logger and fast-logger dependencies

### ISSUE THREAD

**Issue by brendanhay** [kazu-yamamoto/logger#65]
This is more of a question, than a real issue.

Would it not make more sense to define a general interface (class, types, etc.) using `monad-logger`, and then in turn have `fast-logger` depend on `monad-logger` and implement `MonadLogger`?

Are there use cases for using `fast-logger` without the `monad-logger` machinery?

As it is currently, `monad-logger` provides a nice abstraction for loggers in general, but since it has a hard dependency on `fast-logger` it's kind of useless as a general abstraction, since the logger is actually built-in so to speak.

**Comment by snoyberg** [comment]
I've used `monad-logger` in many cases without using the `fast-logger` system for spitting out to stdout/stderr or files. stack is one such example. Besides pulling in an extra library dependency, are you seeing something which actually prevents usage of `monad-logger` in these cases?

**Comment by brendanhay** [comment]
Nothing preventing usage. It's more a case of dependencies and wanting to offer a general logging interface/hook into library internals, but the libraries itself having no necessity for a proper logging subsystem.

Currently I end up exposing something like:

```haskell
data LogLevel
    = Info
    | ...

type Logger = LogLevel -> ByteString -> IO ()
```

And then people convert between my `LogLevel`, log function and `monad-logger, for example.

**Comment by snoyberg** [comment]
Removing the `fast-logger` dependency would mean that users of things like `runStdoutLoggingT` would get slower behavior (or would have to look in a different package for the fast behavior, which would be non-obvious), and may complicate integration significantly due to not being able to use the `Builder`-with-length type. On the other hand, people wanting to use monad-logger today without fast-logger are able to do so, they just have a dependency in place that they don't use. I wouldn't consider this a worthwhile trade-off.

**Comment by brendanhay** [comment]
Thanks
