### ISSUE TITLE
System.Directory: Can't be safely imported!

### ISSUE THREAD

**Issue by k-bx** [kazu-yamamoto/logger#97]
`fast-logger` fails to build on ghcjs built with ghc 8. Might be a ghcjs problem, not sure:

```
    /tmp/stack26927/fast-logger-2.4.6/System/Log/FastLogger/File.hs:6:1: error:
        System.Directory: Can't be safely imported!
        The module itself isn't safe.
```

Tried with `nightly-2016-07-17` snapshot. Please advice if we can remove the `safe` pragma or should we better reach out the ghcjs issue tracker. Thanks!

**Comment by kazu-yamamoto** [comment]
The work for Safe Haskell was done by @rimmington (#68).
I would like to hear advice from him.

**Comment by rimmington** [comment]
It looks like the [patch](https://github.com/ghcjs/ghcjs-boot/blob/ghc-8.0/patches/directory.patch) GHCJS is applying prevents `System.Directory` from being inferred Safe. Since the intent of the `directory` authors is [to have the module inferred Safe](https://github.com/haskell/directory/pull/31), I'd consider this a GHCJS bug.

**Comment by k-bx** [comment]
@rimmington thank you, created https://github.com/ghcjs/ghcjs-boot/issues/37
